// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnltY2BSdvvXIGp-okMqFH8eG72iDa2dM',
    appId: '1:870556665033:web:08250608f5211f94747918',
    messagingSenderId: '870556665033',
    projectId: 'sampleapp-5efc6',
    authDomain: 'sampleapp-5efc6.firebaseapp.com',
    storageBucket: 'sampleapp-5efc6.appspot.com',
    measurementId: 'G-PJ4KYQSN5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx4GuM_Yam2muzoQUO0I28NP0tI1_mTRE',
    appId: '1:870556665033:android:52f246a786103cf5747918',
    messagingSenderId: '870556665033',
    projectId: 'sampleapp-5efc6',
    storageBucket: 'sampleapp-5efc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE_MOrvUkAVMn9tdY_UXSFoKNX9gOdSFU',
    appId: '1:870556665033:ios:e9c5435ba1986846747918',
    messagingSenderId: '870556665033',
    projectId: 'sampleapp-5efc6',
    storageBucket: 'sampleapp-5efc6.appspot.com',
    iosBundleId: 'com.example.nunaCodeChallenges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE_MOrvUkAVMn9tdY_UXSFoKNX9gOdSFU',
    appId: '1:870556665033:ios:e9c5435ba1986846747918',
    messagingSenderId: '870556665033',
    projectId: 'sampleapp-5efc6',
    storageBucket: 'sampleapp-5efc6.appspot.com',
    iosBundleId: 'com.example.nunaCodeChallenges',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnltY2BSdvvXIGp-okMqFH8eG72iDa2dM',
    appId: '1:870556665033:web:8868ded41af97876747918',
    messagingSenderId: '870556665033',
    projectId: 'sampleapp-5efc6',
    authDomain: 'sampleapp-5efc6.firebaseapp.com',
    storageBucket: 'sampleapp-5efc6.appspot.com',
    measurementId: 'G-J78CJ45Q62',
  );
}
